name: Pipeline revisar archivo

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Usar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Construir app con node
        run: npm install

      - name: Verificar si app.js eiste
        run: |
          if [! -f "$GITHUB_WORKSPACE/taller_api/server.js" ]; then
            echo "El archivo app.js no existe."
            exit 1
          fi
            echo "El archivo app.js existe. Continuando..."
