name: Prueba04-27

on:
  push:
    branches: ["main"]

jobs:
  saludo:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Mensaje de mostrar mensaje"
      - name: Fallo intencionado
        run: exit 1
